### ISSUE TITLE
ValueError 

### ISSUE THREAD

**Issue by kuppas** [nikunjmshah/Person-Tracking-and-Re-ID#2]
ValueError: invalid literal for int() with base 10: 'sample1'

**Comment by nikunjmshah** [comment]
The error resulted because of usage of cython while evaluating the person reid ranking. The code for cython based ranking and python based ranking is little different. The cython based code tries to convert the camera id [sample, sample-flip] to integers which results in the error. Simplest way to avoid it is to use python based ranking for person reid. For this you need to modify the file: /root/Person-Tracking-and-Re-ID/deep-reid/torchreid/metrics/rank.py at line 177:
use_cython=True    --->    use_cython=False

I hope this resolves the problem.

**Comment by kuppas** [comment]
I updated the same but value error is not resolved... 
Building train transforms ...
+ resize to 256x128
+ random flip
+ random crop (enlarge to 288x144 and crop 256x128)
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
Building test transforms ...
+ resize to 256x128
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
=> Loading train (source) dataset
Traceback (most recent call last):
  File "finder.py", line 84, in <module>
    transforms=['random_flip', 'random_crop']
  File "/root/Person-Tracking-and-Re-ID/deep-reid/torchreid/data/datamanager.py", line 190, in __init__
    market1501_500k=market1501_500k
  File "/root/Person-Tracking-and-Re-ID/deep-reid/torchreid/data/datasets/__init__.py", line 40, in init_image_dataset
    return __image_datasets[name](**kwargs)
  File "finder.py", line 54, in __init__
    query.append([q_dir + file, int(filename.split('_')[1]), filename.split('_')[0]])
**ValueError: invalid literal for int() with base 10: 'flip'**

**Comment by kuppas** [comment]
Thank You issue resolved

**Comment by AbinJilson** [comment]
when I try to solve that problem as you mentioned ,I got this error
```
File "finder.py", line 132, in <module>
    visrank_topk = 5
  File "/content/Person-Tracking-and-Re-ID/deep-reid/torchreid/engine/engine.py", line 111, in run
    rerank=rerank
  File "/content/Person-Tracking-and-Re-ID/deep-reid/torchreid/engine/engine.py", line 227, in test
    rerank=rerank
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/Person-Tracking-and-Re-ID/deep-reid/torchreid/engine/engine.py", line 302, in _evaluate
    use_metric_cuhk03=use_metric_cuhk03
  File "/content/Person-Tracking-and-Re-ID/deep-reid/torchreid/metrics/rank.py", line 206, in evaluate_rank
    use_metric_cuhk03
  File "/content/Person-Tracking-and-Re-ID/deep-reid/torchreid/metrics/rank.py", line 165, in evaluate_py
    distmat, q_pids, g_pids, q_camids, g_camids, max_rank
  File "/content/Person-Tracking-and-Re-ID/deep-reid/torchreid/metrics/rank.py", line 147, in eval_market1501
    assert num_valid_q > 0, 'Error: all query identities do not appear in gallery'
AssertionError: Error: all query identities do not appear in gallery
```
